---
title: "VECINO K"
subtitle: "ajuste"
author: "Angelica Z
format:
  pdf:
     toc:true
    toc-title: "tabla"
knitr:
  opts_chunk:
    
---

```{r}
pacman:: p_load(tidyverse,
                tidymodels,
                ISLR,
                janitor,
                inspectdf,
                ggally,
                kknn)
```
```{r}
carvan <- Caravan
```

```{r}
tabyl (Caravan$Purchase)

```

```{r}
set.seed(100)
conf_particioman <- initial_split(Caravan, prop = 0.8, strata = Purchase)
caravan_train <- training(conf_particioman)
caravan_test <- testing(conf_particioman)
```

```{r}

knn_spec <- nearest_neighbor() |>
  set_engine("kknn") |>
  set_mode("classification")|>
set_args(neighbors = tune())

         
```

```{r}

rec_spec <- recipe(Purchase ~ ., data=caravan_train) |>
  step_normalize(all_numeric_predictors())
```
```{r}
caraval_wf <- workflow() |>
  add_recipe(rec_spec) |>
  add_model(knn_spec)
```

```{r}
set.seed(10)
folds <- vfold_cv(caravan_train, v = 10, strata = Purchase)



```

```{r}
neighbors <- tibble(neighbors = 1:10)
```

```{r}
tune_res <- tune_grid(
  object = caraval_wf,
  resamples = folds,
  grid = neighbors
)
```
```{r}
save(tune_res, file= "tune_res.RData")
```

